# The list of languages local names
# referd ISO639.2 and wikimedia
#    https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
#
default: &default
  aa: qafar
  ab: аԥсшәа
  af: Afrikaans
  ak: Akana
  am: አማርኛ
  an: Aragonés
  ar: العربية
  as: অসমীয়া
  av: Авар
  ay: Aymar
  az: آذربايجان
  ce: Нохчийн
  ba: Башҡорт
  be: Беларуская
  bg: Български
  bh: भोजपुरी
  bi: Bislama
  bm: Bamanankan
  bn: বাংলা
  bo: བོད་ཡིག
  br: Brezhoneg
  bs: Bosanski
  ca: Català
  ce: Нохчийн
  ch: Chamoru
  co: Corsu
  cr: Nehiyaw
  cs: Česky
  cu: словѣньскъ
  cv: Чăваш
  cy: Cymraeg
  da: Dansk
  de: Deutsch
  dv: ދިވެހިބަސް
  dz: ཇོང་ཁ
  ee: Ɛʋɛ
  en: English
  eo: Esperanto
  es: Español
  et: Eesti
  eu: Euskara
  fa: فارسی
  ff: Fulfulde
  fi: Suomi
  fj: Na Vosa Vakaviti
  fo: Føroyskt
  fr: français
  fy: Frysk
  ga: Gaeilge
  gl: Galego
  gn: Avañe'ẽ
  gv: Gaelg
  ha: هَوُسَ
  he: עברית
  hi: हिन्दी
  ho: Hiri Motu
  ht: Krèyol ayisyen
  hu: Magyar
  hy: հայերեն
  hr: Hrvatski
  hz: Otsiherero
  ia: Interlingua
  id: Bahasa Indonesia
  ie: Interlingue
  ig: Igbo
  ii: ꆇꉙ
  ik: Iñupiak
  io: Ido
  is: Íslenska
  it: Italiano
  iu: ᐃᓄᒃᑎᑐᑦ
  ja: 日本語
  jv: Basa Jawa
  ka: ქართული
  kg: KiKongo
  ki: Gĩkũyũ
  kj: Kuanyama
  kk: Қазақша
  kl: Kalaallisut
  km: ភាសាខ្មែរ
  kn: ಕನ್ನಡ
  ko: 한국어
  kr: Kanuri
  ks:  كشميري
  ku:  كوردی
  kv: Коми
  kw: Kernewek
  ky: Кыргызча
  la: Latina
  lb: Lëtzebuergesch
  lg: Luganda
  li: Limburgs
  ln: Lingála
  lo: ລາວ
  lt: Lietuvių
  lv: Latviešu
  mg: Malagasy
  mh: Kajin Majel
  mi: Māori
  ml: മലയാളം
  mn: Монгол
  mo: Moldovenească
  mr: मराठी
  ms: Bahasa Melayu
  mt: bil-Malti
  my: Myanmasa
  na: Dorerin Naoero
  nd: Sindebele
  ne: नेपाली
  ng: Oshiwambo
  nl: Nederlands
  nn: Norsk (nynorsk)
  "no": Norsk
  nr: isiNdebele
  nv: Diné bizaad
  ny: Chi-Chewa
  oc: Occitan
  oj: ᐊᓂᔑᓈᐯᒧᐎᓐ
  om: Oromoo
  or: ଓଡ଼ିଆ
  os: Иронау
  pa: ਪੰਜਾਬੀ
  pi: Pāli
  pl: Polski
  ps: پښتو
  pt: Português
  qu: Runa Simi
  rm: Rumantsch
  rn: Kirundi
  ro: Română
  ru: Русский
  rw: Kinyarwandi
  sa: संस्कृतम्
  sc: Sardu
  sd: सिनधि
  se: Davvisámegiella
  sg: Sängö
  sh: Srpskohrvatski
  si: සිංහල
  sk: Slovenčina
  sl: Slovenščina
  sm: Gagana Samoa
  sn: chiShona
  so: Soomaaliga
  sq: Shqip
  sr: Српски
  ss: SiSwati
  st: Sesotho
  su: Basa Sunda
  sv: Svenska
  sw: Kiswahili
  ta: தமிழ்
  te: తెలుగు
  tg: Тоҷикӣ
  th: ไทย
  ti: ትግርኛ
  tk: Туркмен
  tl: Tagalog
  tn: Setswana
  to: Lea Faka-Tonga
  tr: Türkçe
  ts: Xitsonga
  tt: Tatarça
  tw: Twi
  ty: Reo Mā`ohi
  ug: Uyƣurqə
  uk: Українська
  ur: اردو
  uz: Ўзбек
  ve: Tshivenḓa
  vi: Việtnam
  wo: Wollof
  xh: isiXhosa
  yi: en:Yiddish
  yo: Yorùbá
  za: Cuengh
  zh: 中文

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
